### ISSUE TITLE
-cclib and -ccopt

### ISSUE THREAD

**Issue by ygrek** [lpw25/namespaces#6]
> -cclib and -ccopt options can be added to .cmxa files so that they are included when linking anything using that library. This feature can probably be replaced by having the same functionality for .cmx files. Possibly some support for deduplicating these options would be necessary as well.

Can be a special file inside a directory, like `.extra_c_options` `.extra_c_options` etc (or one file with key-value options)? Still need to deduplicate when several directories are included though.

**Comment by lpw25** [comment]
See my comments [here](https://github.com/lpw25/namespaces/commit/ff879ec369b420cc75ae000c7c4dbfeeff9a137a). Basically, I don't think it is worth having an additional file format just for this. I think that putting options into `.cmx` files is likely to be just as effective.
